"""Configurable routing rules — the one place routing decisions are
defined. Every rule's rationale cites the specific V0 evidence it's based
on; see experiments/results/v0-mock-baseline.json (generated by
scripts/run_v0_baseline.py) for the underlying numbers.

IMPORTANT CAVEAT, repeated everywhere this matters: that baseline used the
mock provider exclusively (no OPENAI_API_KEY is configured in this
environment). The pattern below is real — genuinely measured, not
fabricated — but it is evidence about how MockProvider's basic-vs-capable
heuristics behave, not a validated finding about real models. Revisit
these rules the moment real provider data exists.
"""

from dataclasses import dataclass

from app.models.enums import TaskCategory, TaskDifficulty
from app.routing.analyzer import RequestAnalysis

ROUTER_VERSION = "v1"

# The 4 categories V0 can actually score (exact_match / classification_label
# / valid_json). The other 4 use evaluation_type=manual and were never
# scored at all.
_DETERMINISTIC_CATEGORIES = frozenset(
    {
        TaskCategory.EXTRACTION,
        TaskCategory.CLASSIFICATION,
        TaskCategory.MATH,
        TaskCategory.STRUCTURED_OUTPUT,
    }
)
_UNSCORED_CATEGORIES = frozenset(
    {
        TaskCategory.SUMMARIZATION,
        TaskCategory.REASONING,
        TaskCategory.CODING,
        TaskCategory.DEBUGGING,
    }
)


@dataclass(frozen=True)
class RoutingRule:
    name: str
    model_id: str
    rationale: str
    categories: frozenset[TaskCategory] | None = None  # None = matches any category
    difficulties: frozenset[TaskDifficulty] | None = None  # None = matches any difficulty

    def matches(self, analysis: RequestAnalysis) -> bool:
        if self.categories is not None and analysis.category not in self.categories:
            return False
        if self.difficulties is not None and analysis.difficulty not in self.difficulties:
            return False
        return True


DEFAULT_RULES: list[RoutingRule] = [
    RoutingRule(
        name="easy-deterministic-to-fast",
        model_id="mock-fast-v1",
        categories=_DETERMINISTIC_CATEGORIES,
        difficulties=frozenset({TaskDifficulty.EASY}),
        rationale=(
            "V0 baseline (experiments/results/v0-mock-baseline.json): on every easy "
            "extraction/classification/math/structured_output task, mock-fast-v1 matched "
            "mock-accurate-v1's correctness exactly (4/4 each) at ~7x lower latency "
            "(71ms vs 522ms avg) and ~29x lower cost. Mock-provider evidence only — no "
            "real model has been measured yet."
        ),
    ),
    RoutingRule(
        name="harder-deterministic-to-accurate",
        model_id="mock-accurate-v1",
        categories=_DETERMINISTIC_CATEGORIES,
        difficulties=frozenset({TaskDifficulty.MEDIUM, TaskDifficulty.HARD}),
        rationale=(
            "V0 baseline (experiments/results/v0-mock-baseline.json): on every medium/hard "
            "extraction/classification/math/structured_output task, mock-fast-v1 was "
            "incorrect (0/4); mock-accurate-v1 was correct on all of them (4/4). "
            "Mock-provider evidence only — no real model has been measured yet."
        ),
    ),
    RoutingRule(
        name="unscored-category-conservative-default",
        model_id="mock-accurate-v1",
        categories=_UNSCORED_CATEGORIES,
        difficulties=None,
        rationale=(
            "summarization/reasoning/coding/debugging use evaluation_type=manual in V0 — "
            "correctness was never actually measured for these categories, so this "
            "defaults to the stronger model rather than assuming the cheaper one is "
            "adequate. Not evidence-based; a conservative fallback under genuine "
            "uncertainty."
        ),
    ),
]

# Reachable only if DEFAULT_RULES is edited to leave a gap — the three
# rules above already cover every (category, difficulty) combination.
# Kept as a safety net since rules are configuration, not a closed system.
DEFAULT_MODEL_ID = "mock-accurate-v1"
DEFAULT_RATIONALE = (
    "No configured routing rule matched this request; defaulting to the strongest "
    "available model as a safety net."
)
